version: "3"

services:
  karassistant-client-discord:
    #build: .
    image: codyisthesenate/karassistant-client-discord:1.1.1
    restart: always
    container_name: karassistant-client-discord
    volumes:
      - .env:/home/node/karAssistant-discordClient/.env
      - ./data:/home/node/karAssistant-discordClient/data
      - ./logs:/home/node/karAssistant-discordClient/logs
    networks:
      - karassistant

networks:
  karassistant:
