version: "3"

services:
  karassistant-back:
    #build: .
    image: codyisthesenate/karassistant-back:1.2.1
    restart: always
    container_name: karassistant-back-${ENV_NAME}
    volumes:
      - .env:/home/node/Karassistant/.env
      - ./data:/home/node/Karassistant/data
      - ./logs:/home/node/Karassistant/logs
    ports:
      - ${PORT_BACK}:3000
    networks:
      - karassistant

networks:
  karassistant:
